import 'dart:io';

import 'dart:typed_data';

import 'package:csv/csv.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:money_control/Models/transaction.dart';
import 'package:money_control/Controllers/currency_controller.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class ExportService {
  // Brand Colors (Approximate matches to Neon/Midnight theme for Print)
  static const PdfColor primaryColor = PdfColor.fromInt(
    0xFF0F172A,
  ); // Dark Blue
  static const PdfColor accentColor = PdfColor.fromInt(0xFF6366F1); // Blurple
  static const PdfColor expenseColor = PdfColor.fromInt(0xFFFF2975); // Pink/Red
  static const PdfColor incomeColor = PdfColor.fromInt(0xFF00E5FF); // Cyan
  static const PdfColor greyLight = PdfColor.fromInt(0xFFF1F5F9);

  static Future<void> exportTransactionsCSV(List<TransactionModel> list) async {
    final rows = <List<dynamic>>[
      [
        "ID",
        "Date",
        "Recipient",
        "Amount",
        "Tax",
        "Total",
        "Currency",
        "Category",
        "Status",
        "Note",
      ],
      ...list.map(
        (tx) => [
          tx.id,
          tx.date.toIso8601String(),
          tx.recipientName,
          tx.amount,
          tx.tax,
          tx.total,
          tx.currency,
          tx.category ?? '',
          tx.status ?? '',
          tx.note ?? '',
        ],
      ),
    ];

    final csv = const ListToCsvConverter().convert(rows);

    final dir = await getApplicationDocumentsDirectory();
    final file = File("${dir.path}/transactions_export.csv");
    await file.writeAsString(csv);

    await OpenFilex.open(file.path);
  }

  static Future<void> exportAnalyticsPDF({
    required List<TransactionModel> filtered,
    required double totalIncome,
    required double totalExpense,
    required double netBalance,
    required String periodLabel,
  }) async {
    final pdf = pw.Document();

    // 1. Calculate Category Data
    final catStats = _calculateCategoryStats(filtered);

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          theme: pw.ThemeData.withFont(
            base: pw.Font.helvetica(),
            bold: pw.Font.helveticaBold(),
          ),
        ),
        build: (ctx) {
          return [
            // Header
            _buildHeader(periodLabel),
            pw.SizedBox(height: 20),

            // Summary Cards
            _buildSummarySection(totalIncome, totalExpense, netBalance),
            pw.SizedBox(height: 30),

            // Category Chart (Visual)
            pw.Text(
              "Top Expense Categories",
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: primaryColor,
              ),
            ),
            pw.SizedBox(height: 10),
            _buildCategoryChart(catStats),
            pw.SizedBox(height: 30),

            // Transactions Table
            pw.Text(
              "Transaction History",
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: primaryColor,
              ),
            ),
            pw.SizedBox(height: 10),
            _buildTransactionsTable(filtered),

            // Footer
            pw.SizedBox(height: 20),
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 5),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  "Generated by Money Control",
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
                pw.Text(
                  DateTime.now().toString().split('.')[0],
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ],
            ),
          ];
        },
      ),
    );

    final Uint8List bytes = await pdf.save();
    final dir = await getApplicationDocumentsDirectory();
    final file = File("${dir.path}/analytics_report.pdf");
    await file.writeAsBytes(bytes);

    await OpenFilex.open(file.path);
  }

  // --- Helper: Header ---
  static pw.Widget _buildHeader(String period) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              "MONEY CONTROL",
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
                color: primaryColor,
              ),
            ),
            pw.Text(
              "Financial Report",
              style: pw.TextStyle(
                fontSize: 12,
                color: PdfColors.grey700,
                letterSpacing: 1.2,
              ),
            ),
          ],
        ),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
          decoration: pw.BoxDecoration(
            color: greyLight,
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Text(
            period,
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: primaryColor,
            ),
          ),
        ),
      ],
    );
  }

  // --- Helper: Summary Section ---
  static pw.Widget _buildSummarySection(double inc, double exp, double net) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        _summaryCard("Total Income", inc, incomeColor),
        _summaryCard("Total Expense", exp, expenseColor),
        _summaryCard(
          "Net Balance",
          net,
          net >= 0 ? PdfColors.green700 : PdfColors.red700,
        ),
      ],
    );
  }

  static pw.Widget _summaryCard(String label, double amount, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        margin: const pw.EdgeInsets.symmetric(horizontal: 4),
        padding: const pw.EdgeInsets.symmetric(vertical: 12, horizontal: 16),
        decoration: pw.BoxDecoration(
          color: PdfColors.white,
          borderRadius: pw.BorderRadius.circular(8),
          border: pw.Border.all(color: PdfColors.grey200),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              label.toUpperCase(),
              style: pw.TextStyle(
                fontSize: 9,
                color: PdfColors.grey600,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              "${CurrencyController.to.currencySymbol.value}${amount.toStringAsFixed(0)}",
              style: pw.TextStyle(
                fontSize: 18,
                color: color,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ],
        ),
      ),
    );
  }

  // --- Helper: Category Chart (Horizontal Bars) ---
  static pw.Widget _buildCategoryChart(List<MapEntry<String, double>> stats) {
    if (stats.isEmpty) {
      return pw.Text(
        "No expense data available.",
        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
      );
    }

    final maxVal = stats.first.value; // stats is sorted desc

    // Take top 5
    final top5 = stats.take(5).toList();

    return pw.Column(
      children: top5.map((e) {
        final cat = e.key;
        final val = e.value;
        final ratio = maxVal > 0 ? (val / maxVal) : 0.0;
        // Let's use actual amount display

        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Row(
            children: [
              // Label
              pw.SizedBox(
                width: 80,
                child: pw.Text(
                  cat,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey800,
                  ),
                ),
              ),
              // Bar
              pw.Expanded(
                child: pw.Stack(
                  alignment: pw.Alignment.centerLeft,
                  children: [
                    pw.Container(
                      height: 12,
                      decoration: pw.BoxDecoration(
                        color: greyLight,
                        borderRadius: pw.BorderRadius.circular(2),
                      ),
                    ),
                    pw.Container(
                      height: 12,
                      width: 250 * ratio, // Max width approx 250 points
                      decoration: pw.BoxDecoration(
                        color: accentColor,
                        borderRadius: pw.BorderRadius.circular(2),
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(width: 10),
              // Amount
              pw.SizedBox(
                width: 60,
                child: pw.Text(
                  "${CurrencyController.to.currencySymbol.value}${val.toStringAsFixed(0)}",
                  textAlign: pw.TextAlign.right,
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  // --- Helper: Transactions Table ---
  static pw.Widget _buildTransactionsTable(List<TransactionModel> txs) {
    if (txs.isEmpty) return pw.Text("No transactions found.");

    // Header
    final headers = ["Date", "Name", "Category", "Amount"];

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: txs.take(50).map((tx) {
        // Limit to 50 for MVP to prevent overflow issues in simple implementation
        final isExpense = tx.senderId == FirebaseAuth.instance.currentUser?.uid;
        final color = isExpense ? expenseColor : incomeColor;
        final sign = isExpense ? "-" : "+";

        return [
          tx.date.toIso8601String().split('T').first,
          tx.recipientName,
          tx.category ?? '-',
          pw.Text(
            "$sign ${CurrencyController.to.currencySymbol.value}${tx.amount.abs().toStringAsFixed(0)}",
            style: pw.TextStyle(color: color, fontSize: 9),
          ),
        ];
      }).toList(),
      headerStyle: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.white,
        fontSize: 10,
      ),
      headerDecoration: const pw.BoxDecoration(color: primaryColor),
      cellStyle: const pw.TextStyle(fontSize: 9, color: PdfColors.grey800),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.centerLeft,
        3: pw.Alignment.centerRight,
      },
      oddRowDecoration: const pw.BoxDecoration(color: greyLight),
      border: null,
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
    );
  }

  // --- Logic: Group Stats ---
  static List<MapEntry<String, double>> _calculateCategoryStats(
    List<TransactionModel> filtered,
  ) {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    final Map<String, double> map = {};

    for (var tx in filtered) {
      // Only expenses for the chart
      if (tx.senderId == uid) {
        final cat = tx.category ?? "Other";
        map[cat] = (map[cat] ?? 0) + tx.amount.abs();
      }
    }

    final sorted = map.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    return sorted;
  }
}
